In [6]:
#-*- coding: utf-8 -*-

import os

from email import policy
from email.parser import BytesParser
from email.parser import Parser

import nltk
from nltk.tokenize import sent_tokenize,word_tokenize
from nltk.corpus import stopwords
from nltk.probability import FreqDist

from string import punctuation
from collections import defaultdict
from heapq import nlargest

from __future__ import print_function
import re
import pandas as pd
import numpy as np
from os import listdir
from collections import Counter
from bs4 import BeautifulSoup
import sklearn
# import xgboost as xgb
import nltk
from sklearn.model_selection import train_test_split
from nltk.stem.snowball import SnowballStemmer
import math 
import gensim
from nltk.tokenize import RegexpTokenizer
stemmer = SnowballStemmer(language='english', ignore_stopwords=True)
tokenizer = RegexpTokenizer(r'[a-z]{3,}')
from matplotlib import pyplot
from sklearn.manifold import TSNE
import matplotlib.pyplot as plt
from matplotlib import pylab
%matplotlib inline

In [180]:
docs_path = 'C:/Users/Artur_Zahreba/Desktop/WorkFusion/P&G/sample email June 15/1.NRO/NRO Emails'

filenames = sorted(listdir(docs_path))
filenames = list(filter(lambda x: re.search(r'\.(msg|MSG)$', x), filenames))
len(filenames)

120

In [48]:
_stopwords = set(stopwords.words('english') + list(punctuation) + 
                 ["pg.com", "from", "sent", "cc", "please", "thank", "subject"])

def getWords(text):
    word_sent = [word for word in word_tokenize(text) if word.lower() not in _stopwords]

    return word_sent

In [10]:
approvers = ["Meng, FanRu", "Liang, Anna"]

def getApprovalText(headers):
    texts = []
    for h in headers:
        c = h.nextSibling
        
        while getattr(c, 'name', None) == 'p':
            text = c.text.encode('ascii', 'replace').decode('utf-8').replace("?","").strip()
            texts.append(text)
            c = c.nextSibling

#     return ' '.join(getWords(' '.join(texts).lower()))
    return ' '.join([t.strip() for t in texts]).strip()

def getDocText(filename):
    with open(docs_path + '/' + filename, 'rb') as fp:
        msg = BytesParser(policy=policy.default).parse(fp)
        msg_text = msg.get_body(preferencelist=('html', 'plain')).get_content()

        soup = BeautifulSoup(str(msg_text), "lxml")

    #     print(len(soup.findAll('div', text = approvers)))
        headers = set()
        
        wordsection = soup.find('div')
        
#         print(wordsection)
        
        if wordsection != None:
            for candidate in wordsection.findAll('div'):
                if candidate.div != None and any("From: "+ appr in candidate.text for appr in approvers):
                    headers.add(candidate)
        fp.close()
        
        return getApprovalText(headers)

In [50]:
 with open("Docs\Approved\FW   Approval  BC OND JFM allowance.msg", 'rb') as fp:
        msg = BytesParser(policy=policy.default).parse(fp)
        msg_text = msg.get_body(preferencelist=('html, plain')).get_content()
        
#         print(msg_text)
        print([w.encode('ascii', 'replace').decode('utf-8').replace("?","").strip() for w in getWords(msg_text.encode('ascii', 'replace').decode('utf-8').replace("?","").strip())])

#         soup = BeautifulSoup(str(msg_text), "lxml")
        
#         text = []
        
#         for block in soup.body.findNextSiblings('p'):
#             text.append(block.text)
            
#         print(' '.join(text).encode('ascii', 'replace').decode('utf-8').replace("?","").strip())
        
#         html_doc = msg_text.encode('ascii', 'replace').decode('utf-8').replace("?","").strip();
#         soup = BeautifulSoup(html_doc, 'html.parser')
#         print(soup.html.body.p.get_text())
#         print(BeautifulSoup.get_text(soup.body).encode('ascii', 'replace').decode('utf-8').replace("?","").strip())
#         print(soup.body.text.encode('ascii', 'replace').decode('utf-8').replace("?","").strip())

#         print(.encode('ascii', 'replace').decode('utf-8').replace("?","").strip())
#         print(str(msg_text.encode('ascii', 'replace').decode('utf-8').replace("?","").strip()))

        fp.close()

['\x11\x1a\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', '\x00\x03\x00', '\x00\x06\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x05\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x10\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00P\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x04\x00\x00\x00\x00\x00\x00\x05\x00\x00\x00\x06\x00\x00\x00\x07\x00\x00\x00\x08\x00\x00\x00', '\x00\x00\x00', '\x00\x00\x00', '\x00\x00\x00', '\x00\x00\x00', '\x00\x00\x00\x0e\x00\x00\x00\x0f\x00\x00\x00\x10\x00\x00\x00\x11\x00\x00\x00\x12\x00\x00\x00\x13\x00\x00\x00\x14\x00\x00\x00\x15\x00\x00\x00\x16\x00\x00\x00', '\x00\x00\x00\x17\x00\x00\x00\x18\x00\x00\x00\x19\x00\x00\x00\x1a\x00\x00\x00\x1b\x00\x00\x00', '\x00\x00\x00', '\x00\x00\x00\x00\x00\x001\x00\x00\x00', '\x00\x00\x00', '\x00\x00\x00', "''", '\x00\x00\x00', '\x00\x00\x00', '\x00\x00\x00', '\x00\x00\x00', "\x00\x00\x00'\x00\x00\x00", '\x00\x00\x00', '\x00\x00\x00*\x00\x00\x00+\x00\x00\x00', '\x00\x00\x0

In [300]:
getDocText(filenames[0])

'Approved.'

In [301]:
doc_texts = []
doc_msgs = []

for filename in filenames:
    #         text_bs = BeautifulSoup(str(msg_text), 'html.parser')
    text = getDocText(filename)

    #         doc_texts.append(("Approved", filename, text))
    doc_texts.append(text)
    doc_msgs.append(msg)
            
print(len(doc_texts))

120


In [298]:
doc_texts

['approved',
 'approve anna',
 'approve behalf anna',
 '',
 'approve anna',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 'approve anna',
 'approved',
 '',
 '',
 'approve anna',
 'approve anna',
 'hi josephine ok get back create po ms p channel io hi clef kindly ask eunice help',
 'approve anna',
 'approved',
 'approve anna hi dear batch require previous customer help hand carry anna approve anna ok cool hi eunice would pls kindly help drop nro accordingly anna',
 'approve anna',
 '',
 'approve anna',
 'approve anna',
 'approve anna',
 'approved',
 'approve anna hi wenyi confirmed would loose sample without pre-pack support directly dfs thx eunices help check inventory let us know execute anna',
 '',
 'approve anna',
 'approve anna',
 'approve anna',
 'approve anna',
 '',
 'approve anna',
 'hi dongin yes packed set pls find sending history dc feel free let know help needed dear wenyi let support one batch gwp help close case long term since jeju order monthly regular per-previousl

In [259]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [260]:
vectorizer = TfidfVectorizer(
    max_df = 0.5,
    min_df = 2,
    stop_words = 'english'
)

In [261]:
X = vectorizer.fit_transform(doc_texts)
X

<120x19 sparse matrix of type '<class 'numpy.float64'>'
	with 116 stored elements in Compressed Sparse Row format>

In [288]:
from sklearn.cluster import KMeans

number_of_classes = 2

km = KMeans(
    n_clusters = number_of_classes, 
    init = 'k-means++', 
    max_iter = 500, 
    n_init = 1, 
    verbose = True
)
km

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=500,
    n_clusters=2, n_init=1, n_jobs=1, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=True)

In [289]:
km.fit(X)

Initialization complete
Iteration  0, inertia 10.828
Iteration  1, inertia 10.360
Converged at iteration 1: center shift 0.000000e+00 within tolerance 1.419477e-06


KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=500,
    n_clusters=2, n_init=1, n_jobs=1, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=True)

In [290]:
np.unique(km.labels_, return_counts=True)

(array([0, 1]), array([89, 31], dtype=int64))

In [291]:
text = {}
for i, cluster in enumerate(km.labels_):
    oneDocument = doc_texts[i]
    if cluster not in text.keys():
        text[cluster] = oneDocument
    else:
        text[cluster] += oneDocument
km.labels_

array([0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0])

In [292]:
keywords = {}
counts = {}

for cluster in range(number_of_classes):
    word_sent = word_tokenize(text[cluster])
#     word_sent = [word for word in word_sent if word.lower() not in _stopwords]
    freq = FreqDist(word_sent)
    keywords[cluster] = nlargest(20, freq, key=freq.get)
    counts[cluster]=freq
keywords

{0: ['hi',
  'help',
  'anna',
  'eunice',
  'batch',
  'nro',
  'would',
  'support',
  'let',
  'dc',
  'gwp',
  'order',
  'quarter',
  '1',
  'ronnie',
  'ok',
  'back',
  'kindly',
  'dear',
  'pls'],
 1: ['annaapprove', 'approve', 'anna', 'behalf', 'thx']}

In [293]:
unique_keys = {}

for cluster in range(2):   
    other_clusters = list(set(range(2)) - set([cluster]))
    keys_other_clusters = set(keywords[other_clusters[0]]).union(set(keywords[other_clusters[0]]))
    unique = set(keywords[cluster]) - keys_other_clusters
    unique_keys[cluster] = nlargest(10, unique, key=counts[cluster].get)
    
unique_keys

{0: ['hi',
  'help',
  'nro',
  'eunice',
  'batch',
  '1',
  'quarter',
  'support',
  'would',
  'let'],
 1: ['annaapprove', 'approve', 'thx', 'behalf']}

In [294]:
approval_text = "I approve on behalf of Anna"

In [295]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 3)
classifier.fit(X, km.labels_)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')

In [296]:
test = vectorizer.transform([approval_text.encode('ascii', errors='ignore').decode('utf8')])

In [297]:
classifier.predict(test)

array([1])

In [ ]:
# If we want to print a priview of the message content, we can extract whatever
# the least formatted payload is and print the first three lines.  Of course,
# if the message has no plain text part printing the first three lines of html
# is probably useless, but this is just a conceptual example.
simplest = msg.get_body(preferencelist=('related', 'html', 'plain'))
print()
email_full_text = ''.join(simplest.get_content().splitlines(keepends=True)[:120])
print(email__full_text)